name: CI Learning

on:
  push:
    branches:
      - ci-learning

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Show repository files
        run: |
          pwd
          ls -la